"""add_session_state_jsonb

Revision ID: 69b1bac8c821
Revises: ddfa319311d9
Create Date: 2026-06-19 03:52:37.203016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69b1bac8c821'
down_revision: Union[str, None] = 'ddfa319311d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.alter_column('interview_sessions', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('interview_sessions', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint('interview_sessions_company_id_fkey', 'interview_sessions', type_='foreignkey')
    op.drop_constraint('interview_sessions_user_id_fkey', 'interview_sessions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('interview_sessions_user_id_fkey', 'interview_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('interview_sessions_company_id_fkey', 'interview_sessions', 'companies', ['company_id'], ['id'])
    op.alter_column('interview_sessions', 'date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('interview_sessions', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='playing_with_neon_pkey')
    )
    # ### end Alembic commands ###
